// Run: node tools/check_intake_ui.cjs. Uses the actual page handlers without a browser.
const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const listeners = {}, nodes = new Map();
const node = id => {
  if (!nodes.has(id)) nodes.set(id, {id, value:'', dataset:{}, events:{}, addEventListener(type,fn){this.events[type]=fn;}, classList:{toggle(){}}, hidden:false});
  return nodes.get(id);
};
const context = vm.createContext({
  document:{getElementById:node, addEventListener(type, fn){(listeners[type] ||= []).push(fn);},
    body:{setAttribute(){},removeAttribute(){}},querySelectorAll(){return [];},querySelector(){return null;}},
  localStorage:{getItem(){},setItem(){}},sessionStorage:{getItem(){},setItem(){}},
  crypto:require('node:crypto').webcrypto, console, setTimeout, clearTimeout, URLSearchParams,
  Event:class {constructor(type){this.type=type;}}
});
const code = fs.readFileSync(require('node:path').join(__dirname,'../static/app.js'),'utf8');
vm.runInContext(code.replace(/^boot\(\);$/m,''), context);
const run = code => vm.runInContext(code, context);
const originalShowDoc=run('showDoc');
const originalLoadContractItems=run('loadContractItems'), originalLoadRecognitionList=run('loadRecognitionList');
// Batch sequences must remain unique beyond the 99th receipt.
node('batch-number').value='100';
assert.equal(run('composeBatch()'),'B100');
node('batch-number').value='101';
assert.equal(run('composeBatch()'),'B101');
for(const value of ['0','-1','1.5','1e2','1000000000000','']){
  node('batch-number').value=value;
  assert.equal(run('composeBatch()'),'','invalid sequence: '+value);
}
node('batch-number').value='001';
assert.equal(run('composeBatch()'),'B01');
node('batch-number').value='1';
// Searching a box's contents must reveal its parent batch/box; reset keeps stock intact.
run("db={stock:[{id:1,code:'X1',name:'转轮箱',package:'A1',batch:'B01',box:'7-4',qty:1,unit:'箱',warehouse:'主仓库',bin:'待分配',state:'AVAILABLE',contents:[{name:'轴承',qty:2,unit:'个'}]},{id:2,code:'X2',name:'高压柜',package:'A1',batch:'B02',box:'8',qty:4,unit:'台',state:'PENDING',contents:[]}],segments:[{code:'A1',zh:'标段一',en:'Lot 1'}]};treeState.query='轴承';");
const stockBefore=run('JSON.stringify(db.stock)');
const flat=run('inventoryTreeHTML()');
assert.ok(flat.includes('data-stock-issue="1"') && flat.includes('data-stock-view="1"'));
run('queueStockForIssue(1)');
assert.equal(run('cart[0].stock_id'),1);
assert.equal(run('issueMode'),'position');
assert.throws(()=>run('queueStockForIssue(2)'),/可用/);
assert.equal(run('JSON.stringify(db.stock)'),stockBefore);
assert.ok(run('treeLeaf(db.stock[0])').includes('data-stock-issue="1"'));
run("action='OUT';issueMode='position';cart=[{stock_id:1,qty:0.5}];syncBulkCart();");
assert.equal(run('cart[0].qty'),0.5);
assert.equal(run('cart[0].stock_id'),1);
run("preview={source_rows:[{id:'bulk1',source_row:1,issues:['缺少单位'],raw:[],evidence:{},suggestions:{}}]};intakeCorrections={};intakeOnlyProblems=true;renderIntakeEditor();handleIntakeAction('intake-exclude-page',{});handleIntakeAction('intake-restore-page',{});");
assert.equal(run('intakeCorrections.bulk1.exclude_reason'),'');
assert.ok(run('intakeFieldIssues(preview.source_rows[0],"unit").length')>0);
run("cart=[];inventoryLayout='box';");
const matches=run('inventoryTreeHTML()');
assert.equal(run('filteredTreeRows().length'),1);
assert.ok(matches.includes('class="tree-batch" open') && matches.includes('class="tree-box" open'));
assert.ok(matches.includes('筛选到') && matches.includes('data-tree-reset') && !matches.includes('高压柜'));
assert.ok(matches.includes('aria-label="搜索库存"'));
run("renderInventoryTree=()=>{}; treeState.contract='A1';treeState.batch='B01';treeState.state='AVAILABLE';treeState.sort='item';");
const clearFilters={dataset:{treeReset:'true'},closest(){return this;}};
listeners.click[0]({target:clearFilters});
assert.equal(run('treeState.query'), '');
assert.equal(run('treeState.batch'), '');
assert.equal(run('treeState.state'), '');
assert.equal(run('filteredTreeRows().length'),2);
assert.equal(run('JSON.stringify(db.stock)'),stockBefore);
// Remove and restore the same row, including one already excluded in the snapshot.
const toggle={dataset:{action:'intake-toggle-row'},textContent:'移除'};
const reason={value:''};
const row={classList:{toggle(){}},querySelector(selector){return selector==='[data-intake-include]'?check:selector.includes('exclude_reason')?reason:toggle;}};
const check={id:'',dataset:{intakeInclude:'r1'},checked:true,closest(){return row;},dispatchEvent(e){listeners[e.type].forEach(fn=>fn({target:this}));}};
toggle.closest=()=>row;
context.toggle=toggle;
run("intakeCorrections={r1:{name:'修正名称'}}; handleIntakeAction('intake-toggle-row',toggle);");
assert.equal(check.checked,false);
assert.equal(toggle.textContent,'恢复');
assert.equal(run('intakeCorrections.r1.name'),'修正名称');
run("handleIntakeAction('intake-toggle-row',toggle);");
assert.equal(check.checked,true);
assert.equal(run('intakeCorrections.r1.exclude_reason'),'');
assert.equal(toggle.textContent,'移除');
assert.equal(node('intake-submit').dataset.action,'import-confirm');
const manual=run("manualRowHTML({code:'<原编码>',drawing:'D01'})");
assert.ok(manual.includes('&lt;原编码&gt;') && manual.includes('D01'));
assert.ok(manual.indexOf('data-manual-field="code"')>manual.indexOf('<details'));
// Real confirmation handler must revalidate; blocked results must never post.
const calls=[];
context.testApi=async(path,payload)=>{calls.push({path,payload:JSON.parse(JSON.stringify(payload))});return path==='/api/preview'?{errors:context.errors,recognition_id:42}:{id:7};};
run("api=testApi; renderPreview=()=>{}; refresh=async()=>{}; showDoc=async()=>{}; db={segments:[{code:'A1'}]}; intakeMode='paste'; intakeInputs=[{source:'paste',role:'packing_detail',text:'名称\\t数量'}]; intakeCorrections={r1:{qty:'12'},r2:{exclude_reason:'人工选择不入库'}};");
for (const [id,value] of Object.entries({'default-package':'A1','batch-number':'1','batch-date':'2026-10-01','operator':'TEST','default-warehouse':'主仓库','default-bin':'待分配','default-state':'AVAILABLE','intake-text-packing_detail':'名称\t数量'})) node(id).value=value;
const submit=node('intake-submit');submit.closest=()=>submit;
async function click(errors){
  context.errors=errors;
  listeners.click[0]({target:submit});
  for(let i=0;i<100&&run('posting');i++) await new Promise(resolve=>setImmediate(resolve));
  assert.equal(run('posting'),false);
}
(async()=>{
  await click(['第2行缺少单位']);
  assert.deepEqual(calls.map(x=>x.path),['/api/preview']);
  run('markIntakeDirty()');
  await click([]);
  assert.deepEqual(calls.map(x=>x.path),['/api/preview','/api/preview','/api/import']);
  const saved=calls.at(-1).payload;
  assert.equal(saved.corrections.r1.qty,'12');
  assert.equal(saved.corrections.r2.exclude_reason,'人工选择不入库');
  assert.equal(saved.recognition_id,42);
  assert.equal(saved.defaults.package,'A1');
  assert.equal(saved.defaults.batch,'B01');
  run("preview={source_rows:[{id:'ai-row',source_row:2,name:'原名称',issues:[],raw:[],evidence:{},suggestions:{},ai_suggestions:{name:'建议名称'}}]};intakeCorrections={};");
  const beforeAdoption=calls.length;
  assert.equal(run('Object.keys(intakeCorrections).length'),0);
  run("handleIntakeAction('intake-ai-accept',{dataset:{rowId:'ai-row'}})");
  assert.equal(run("intakeCorrections['ai-row'].name"),'建议名称');
  assert.equal(calls.length,beforeAdoption,'adopting a suggestion must not post stock');
  let prompts=0;
  context.window={confirm:()=>true};context.prompt=()=>{prompts++;return '123';};
  calls.length=0;
  const deleteButton={dataset:{delete:'7'},closest(){return this;}};
  listeners.click[0]({target:deleteButton});
  for(let i=0;i<100&&run('posting');i++) await new Promise(resolve=>setImmediate(resolve));
  assert.equal(prompts,1);
  assert.deepEqual(calls[0],{path:'/api/delete',payload:{id:'7',password:'123'}});
  run("db.admin_password_configured=true;deleteSelected=[7];");
  node('delete-password').value='123';submit.dataset.action='delete-post';
  await click([]);
  assert.deepEqual(calls.at(-1),{path:'/api/delete-batch',payload:{ids:[7],password:'123'}});
  assert.equal(prompts,1);
  run("db.documents=[{id:7,kind:'IN'},{id:8,kind:'BASELINE'},{id:9,kind:'IN',reversed_by:10}];loadRecognitionList=async()=>{};");
  assert.ok(run('recognitionDeleteActions({id:42,document_id:7})').includes('data-delete="7"'));
  for (const id of [8,9,null]) assert.ok(!run(`recognitionDeleteActions({id:42,document_id:${id}})`).includes('data-delete='));
  const archiveButton={dataset:{action:'recognition-delete',recognitionId:'42'},closest(){return this;}};
  calls.length=0;
  listeners.click[0]({target:archiveButton});
  for(let i=0;i<100&&run('posting');i++) await new Promise(resolve=>setImmediate(resolve));
  assert.equal(prompts,2);
  assert.deepEqual(calls,[{path:'/api/recognition/delete-batch',payload:{ids:[42],password:'123'}}]);
  context.window.confirm=()=>false;
  listeners.click[0]({target:archiveButton});
  for(let i=0;i<100&&run('posting');i++) await new Promise(resolve=>setImmediate(resolve));
  assert.equal(prompts,2);
  assert.equal(calls.length,1);
  run('recognitionListRows=[{id:42},{id:43}];recognitionSelected.clear();');
  const selectAll={id:'',dataset:{recognitionAll:''},checked:true};
  listeners.change.forEach(fn=>fn({target:selectAll}));
  assert.equal(run('recognitionSelected.size'),2);
  const selectedRow={id:'',dataset:{recognitionSelect:'43'},checked:false};
  listeners.change.forEach(fn=>fn({target:selectedRow}));
  assert.equal(run('recognitionSelected.has(43)'),false);
  selectedRow.checked=true;
  listeners.change.forEach(fn=>fn({target:selectedRow}));
  context.window.confirm=()=>true;
  const bulkArchiveButton={dataset:{action:'recognition-delete-batch'},closest(){return this;}};
  calls.length=0;
  listeners.click[0]({target:bulkArchiveButton});
  for(let i=0;i<100&&run('posting');i++) await new Promise(resolve=>setImmediate(resolve));
  assert.equal(prompts,3);
  assert.deepEqual(calls,[{path:'/api/recognition/delete-batch',payload:{ids:[42,43],password:'123'}}]);
  assert.equal(run('recognitionSelected.size'),0);
  run("intakeMode='upload';intakeInputs=[];intakeCorrections={};fileData=async file=>({filename:file.name,content:'dGVzdA=='});");
  node('intake-role-main').value='auto';
  node('intake-file-packing_detail').files=[];
  node('intake-file-arrival_note').files=[{name:'arrival.xls'}];
  await run('prepareIntake()');
  run("intakeCorrections={'0:Sheet:2':{qty:'8'}}");
  await run('prepareIntake()');
  assert.equal(run('intakeInputs.length'),1,'secondary-only upload must not duplicate on confirm');
  assert.equal(run("intakeCorrections['0:Sheet:2']?.qty"),'8');
  run("db={stock:[{id:1,code:'A',name:'A',unit:'个',qty:10,state:'AVAILABLE'},{id:2,code:'A',name:'A',unit:'个',qty:10,state:'AVAILABLE'},{id:3,code:'B',name:'B',unit:'个',qty:10,state:'AVAILABLE'}],segments:[]};cart=[{stock_id:2,qty:2}];issueMode='item';action='OUT';");
  assert.match(run('bulkIssueHTML()'),/data-group-qty="0"[^>]*value="2"/,'redraw restores pending quantity');
  const groupFields=[{value:'2',classList:{toggle(){}}},{value:'1',classList:{toggle(){}}}];
  const groupChecks=[{checked:true},{checked:true}];
  context.document.querySelector=selector=>{
    const match=selector.match(/data-group-(qty|check)="(\d+)"/);
    if(match)return (match[1]==='qty'?groupFields:groupChecks)[Number(match[2])];
    return selector==='[data-action="post"]'?node('out-post'):null;
  };
  run('syncBulkCart()');
  assert.equal(run('cart.find(r=>r.stock_id===2)?.qty'),2,'editing B preserves exact A stock position');
  assert.equal(run('cart.some(r=>r.stock_id===1)'),false);
  run("setCartQuantity(0,'3')");
  assert.equal(groupFields[0].value,'3');
  run('syncBulkCart()');
  assert.equal(run('cart.find(r=>r.stock_id===2)?.qty'),'3','manual cart quantity survives next group edit');
  assert.match(run('cartHTML()'),/data-cart="0"[^>]*step="1"[^>]*min="0"/,'quantity arrows use integer steps with zero base');
  assert.match(run('bulkIssueHTML()'),/step="1"[^>]*data-group-qty="0"/);
  assert.ok(!code.includes('step="0.000001"'),'no tiny spinner steps in stock quantities');
  run("setCartQuantity(0,'0.25');syncBulkCart()");
  assert.equal(run('cart.find(r=>r.stock_id===2)?.qty'),'0.25','manual decimal quantity remains exact');
  assert.ok(run('cartHTML()').includes('data-cart-remark="0"'),'each pending issue line offers a remark');
  const remarkInput={id:'',dataset:{cartRemark:'0'},value:'用于 A 区\n配件另交'};
  listeners.input.forEach(fn=>fn({target:remarkInput}));
  run('syncBulkCart()');
  assert.equal(run('cart.find(r=>r.stock_id===2)?.remark'),remarkInput.value);
  groupFields[0].value='4';
  run('syncBulkCart()');
  assert.equal(run('cart.find(r=>r.stock_id===2)?.remark'),remarkInput.value,'quantity edits keep the selected box remark');
  assert.ok(run('cartHTML()').includes('用于 A 区'));
  context.document.querySelectorAll=selector=>selector==='[data-group-check]'?groupChecks.map((check,i)=>({...check,dataset:{groupCheck:String(i)}})):[];
  run('addSelectedGroups()');
  assert.equal(run('cart.find(r=>r.stock_id===2)?.remark'),remarkInput.value,'all group-add paths preserve box notes');
  // Use the real checkbox/clear/input handlers: an unchecked item cannot stay in cart.
  groupChecks.forEach((check,i)=>{check.id='';check.dataset={groupCheck:String(i)};});
  groupFields.forEach((field,i)=>{field.id='';field.dataset={groupQty:String(i)};});
  context.document.querySelectorAll=selector=>selector==='[data-group-check]'?groupChecks:selector==='[data-group-qty]'?groupFields:selector==='[data-out-group]:not([hidden]) [data-group-check]'?groupChecks:[];
  groupChecks[0].checked=false;
  listeners.change.forEach(fn=>fn({target:groupChecks[0]}));
  assert.equal(groupFields[0].value,'');
  assert.equal(run('cart.some(r=>r.stock_id===2)'),false,'unchecking removes that material');
  groupFields[0].value='3';listeners.input.forEach(fn=>fn({target:groupFields[0]}));
  assert.equal(groupChecks[0].checked,true);
  assert.equal(run('cart.some(r=>r.stock_id===1)'),true,'typing a positive quantity includes the item');
  const clearIssue={dataset:{outBulk:'clear'},closest(){return this;}};
  listeners.click[0]({target:clearIssue});
  assert.equal(run('cart.length'),0);
  assert.ok(groupFields.every(field=>field.value===''));
  assert.ok(groupChecks.every(check=>!check.checked));
  assert.equal(node('out-post').disabled,true);
  groupFields[0].value='3';listeners.input.forEach(fn=>fn({target:groupFields[0]}));
  run("setCartQuantity(0,'0')");
  assert.equal(run('cart.length'),0,'zero removes an individual position too');
  assert.equal(groupChecks[0].checked,false);
  // Pending requests block page/language redraw and lock native controls.
  const previousDraw=run('draw');let redraws=0;
  context.redraw=()=>{redraws++;};run("draw=redraw;page='outbound'");
  let finishWork;context.pendingWork=()=>new Promise(resolve=>finishWork=resolve);
  const pending=run('work(pendingWork)');
  const goInbound={dataset:{page:'inbound'},closest(){return this;}};
  listeners.click[0]({target:goInbound});node('lang').events.click();
  assert.equal(run('page'),'outbound');assert.equal(redraws,0);
  assert.equal(node('view').inert,true);assert.equal(node('nav').inert,true);
  finishWork();await pending;
  assert.equal(node('view').inert,false);assert.equal(run('posting'),false);
  // Repaint stubs remove DOM inputs like innerHTML; actual handlers must restore drafts.
  let activeForm='inbound',manualRows=[];
  const groupSelector=context.document.querySelector;
  context.document.querySelector=selector=>selector==='.intake-entry'?(activeForm==='inbound'?node('receipt-panel'):null):selector==='#out-operator'?(activeForm==='outbound'?node('out-operator'):null):groupSelector(selector);
  const groupAll=context.document.querySelectorAll;
  context.document.querySelectorAll=selector=>selector==='#intake-manual-rows tr'?manualRows:groupAll(selector);
  context.repaint=()=>{
    activeForm=run('page');
    for(const id of [...run('receiptDraftFields'),...run('issueDraftFields')])node(id).value='';
    node('intake-file-packing_detail').files=[];node('intake-file-arrival_note').files=[];
    run('restoreBusinessDraft()');
  };
  run("draw=repaint;preview=null;receiptDraft={};issueDraft={};intakeFiles={};manualDraftRows=null;page='inbound';intakeMode='paste';intakeInputs=[]");
  const receiptValues={'intake-text-packing_detail':'名称\t数量\t单位\n电缆\t3\t米','batch-number':'100','batch-date':'2026-10-02','operator':'仓管甲','party':'厂家A','default-package':'A1','default-warehouse':'主仓库','default-bin':'临时位','default-state':'PENDING'};
  Object.entries(receiptValues).forEach(([id,value])=>node(id).value=value);
  const goInventory={dataset:{page:'inventory'},closest(){return this;}};
  listeners.click[0]({target:goInventory});listeners.click[0]({target:goInbound});
  Object.entries(receiptValues).forEach(([id,value])=>assert.equal(node(id).value,value,'receipt draft '+id));
  node('lang').events.click();
  assert.equal(node('intake-text-packing_detail').value,receiptValues['intake-text-packing_detail']);
  run('refresh=async()=>draw()');node('refresh').events.click();
  for(let i=0;i<100&&run('posting');i++)await new Promise(resolve=>setImmediate(resolve));
  assert.equal(node('batch-number').value,'100');assert.equal(run('composeBatch()'),'B100');
  const chosenFile={name:'厂家测试.xls'};node('intake-file-packing_detail').files=[chosenFile];run("intakeMode='upload'");
  listeners.click[0]({target:goInventory});listeners.click[0]({target:goInbound});
  assert.equal(run('intakeFiles.packing_detail'),chosenFile,'keep File object across repaint');
  assert.ok(run('intakeEntryHTML()').includes(chosenFile.name));
  await run('prepareIntake()');assert.equal(run('intakeInputs[0].filename'),chosenFile.name);
  run("intakeMode='manual'");manualRows=[{querySelectorAll(){return [{dataset:{manualField:'name'},value:'未识别手工物资'},{dataset:{manualField:'qty'},value:'2'},{dataset:{manualField:'unit'},value:'个'}];}}];
  listeners.click[0]({target:goInventory});manualRows=[];listeners.click[0]({target:goInbound});
  assert.ok(run('intakeEntryHTML()').includes('未识别手工物资'));
  const goIssue={dataset:{page:'outbound'},closest(){return this;}};
  listeners.click[0]({target:goIssue});
  const issueValues={'out-operator':'仓管乙','out-party':'施工班组','out-purpose':'A区安装','out-search':'A'};
  Object.entries(issueValues).forEach(([id,value])=>node(id).value=value);
  groupFields[0].value='2';listeners.input.forEach(fn=>fn({target:groupFields[0]}));
  listeners.click[0]({target:goInventory});listeners.click[0]({target:goIssue});
  Object.entries(issueValues).forEach(([id,value])=>assert.equal(node(id).value,value,'issue draft '+id));
  assert.equal(run('cart.reduce((n,r)=>n+Number(r.qty),0)'),2);
  assert.match(run('bulkIssueHTML()'),/data-group-qty="0"[^>]*value="2"/);
  node('lang').events.click();assert.equal(node('out-purpose').value,'A区安装');
  node('refresh').events.click();for(let i=0;i<100&&run('posting');i++)await new Promise(resolve=>setImmediate(resolve));
  assert.equal(node('out-party').value,'施工班组');
  context.drawBack=previousDraw;run('draw=drawBack');
  context.remarkDoc={id:7,kind:'OUT',number:'OUT-TEST',created:'2026-10-01',operator:'TEST',party:'A 区',purpose:'安装用',lines:[{code:'A',name:'物资A',qty:-0.25,unit:'米',remark:'<请核对>\n配件另交'}]};
  run('api=async()=>remarkDoc');
  node('modal').showModal=()=>{};
  await originalShowDoc(7);
  assert.ok(node('modal-body').innerHTML.includes('document-line-remark'));
  assert.ok(node('modal-body').innerHTML.includes('&lt;请核对&gt;\n配件另交'));
  assert.ok(node('modal-body').innerHTML.includes('<th>备注</th>'));
  // Resolve a newer segment before the older request: old data must not replace it.
  const pendingReads=[];
  context.pendingRead=path=>new Promise((resolve,reject)=>pendingReads.push({path,resolve,reject}));
  run("api=pendingRead;contractState={code:'A1',ready:true,loading:false,rows:[],total:0,hasMore:false}");
  const oldSegment=originalLoadContractItems(false);
  run("contractState={code:'A2',ready:true,loading:false,rows:[],total:0,hasMore:false}");
  const newSegment=originalLoadContractItems(false);
  assert.ok(pendingReads[0].path.includes('package=A1'));assert.ok(pendingReads[1].path.includes('package=A2'));
  pendingReads[1].resolve({rows:[{code:'CURRENT',name:'当前标段'}],total:1,has_more:false});await newSegment;
  pendingReads[0].resolve({rows:[{code:'STALE',name:'旧标段'}],total:1,has_more:false});await oldSegment;
  assert.equal(run('contractState.code'),'A2');
  assert.equal(run('contractState.rows[0].code'),'CURRENT','late old response must not overwrite A2');
  // Leaving the archive during a failed read cannot write a missing node.
  const originalGet=context.document.getElementById;
  let recognitionHost=node('recognition-list');
  context.document.getElementById=id=>id==='recognition-list'?recognitionHost:originalGet(id);
  run('recognitionListLoading=false;recognitionListRows=[];recognitionListOffset=0');
  const failedArchive=originalLoadRecognitionList(false),failedRead=pendingReads.at(-1);
  recognitionHost=null;failedRead.reject(new Error('late archive failure'));
  await assert.doesNotReject(failedArchive);
  assert.equal(run('recognitionListLoading'),false);
  // If the archive was recreated meanwhile, ignore old rows and read for the new node.
  recognitionHost={innerHTML:'new archive'};
  context.actualArchiveLoader=originalLoadRecognitionList;run('loadRecognitionList=actualArchiveLoader;renderRecognitionList=()=>{}');
  const staleArchive=originalLoadRecognitionList(false),staleRead=pendingReads.at(-1);
  recognitionHost={innerHTML:'reopened archive'};run('loadRecognitionList(false)');
  staleRead.resolve({rows:[{id:1}],total:1,has_more:false});await staleArchive;
  assert.equal(run('recognitionListRows.length'),0,'old archive must not populate the reopened page');
  assert.notEqual(pendingReads.at(-1),staleRead,'reopened archive must start its own read');
  pendingReads.at(-1).resolve({rows:[{id:2}],total:1,has_more:false});
  for(let i=0;i<100&&run('recognitionListLoading');i++)await new Promise(resolve=>setImmediate(resolve));
  assert.equal(run('recognitionListRows[0].id'),2);
  context.document.getElementById=originalGet;
  console.log('PASS: batch sequences, draft preservation, busy controls, issue selection, intake confirmation and password-only deletion');
})().catch(error=>{console.error(error);process.exitCode=1;});
