param([string]$InstallDir, [switch]$Quiet)
$ErrorActionPreference = 'Stop'
try {
    if (-not $InstallDir) { $InstallDir = Split-Path -Parent $PSScriptRoot }
    $requestedRoot = $InstallDir
    . (Join-Path $PSScriptRoot 'Install.ps1') -InstallDir $requestedRoot -LibraryOnly
    $root = Get-SafeRoot $InstallDir
    if ($root -ne (Split-Path -Parent $PSScriptRoot)) { throw 'Uninstaller must run from the installation being removed.' }
    $manifest = Get-Content -LiteralPath (Join-Path $root 'release-manifest.json') -Raw -Encoding UTF8 | ConvertFrom-Json
    if ($manifest.format -ne 1 -or -not $manifest.files -or -not (Test-Path -LiteralPath (Join-Path $root 'server.py'))) { throw 'Installed application marker is missing.' }
    $files = @($manifest.files.PSObject.Properties.Name) + @('release-manifest.json')
    foreach ($name in $files) { Get-SafeFile $root $name | Out-Null }
    if (-not $Quiet) {
        Add-Type -AssemblyName System.Windows.Forms
        $choice = [Windows.Forms.MessageBox]::Show("卸载智能仓储程序？`n库存、单据、备份和模型将保留在：`n$root", $appName, [Windows.Forms.MessageBoxButtons]::YesNo, [Windows.Forms.MessageBoxIcon]::Question)
        if ($choice -ne [Windows.Forms.DialogResult]::Yes) { exit 0 }
    }
    Stop-OwnedApp $root | Out-Null
    $shell = New-Object -ComObject WScript.Shell
    foreach ($folder in @([Environment]::GetFolderPath('Desktop'), (Join-Path ([Environment]::GetFolderPath('Programs')) $appName))) {
        $path = Join-Path $folder ($appName + '.lnk')
        if (Test-Path -LiteralPath $path) {
            $shortcut = $shell.CreateShortcut($path)
            if ($shortcut.TargetPath -eq (Join-Path $root 'runtime\pythonw.exe')) { Remove-Item -LiteralPath $path -Force }
        }
    }
    if ((Test-Path -LiteralPath $registryPath) -and (Get-ItemProperty -LiteralPath $registryPath).InstallLocation -eq $root) { Remove-Item -LiteralPath $registryPath -Recurse -Force }
    foreach ($name in $files) {
        $path = Get-SafeFile $root $name
        if (Test-Path -LiteralPath $path -PathType Leaf) { Remove-Item -LiteralPath $path -Force }
    }
    # Only program folders and generated bytecode; do not traverse user data.
    $directories = @{}
    foreach ($name in $files) {
        $parent = Split-Path -Parent (Join-Path $root $name)
        while ($parent.Length -gt $root.Length) { $directories[$parent]=$true; $parent=Split-Path -Parent $parent }
    }
    foreach ($programDir in @('runtime','tools','__pycache__')) {
        $path = Join-Path $root $programDir
        if (-not (Test-Path -LiteralPath $path -PathType Container)) { continue }
        Get-SafeRoot $path | Out-Null
        $caches = if ($programDir -eq '__pycache__') { @(Get-Item -LiteralPath $path) } else { @(Get-ChildItem -LiteralPath $path -Directory -Filter '__pycache__' -Recurse -Force) }
        foreach ($cache in $caches) {
            $safe = Get-SafeRoot $cache.FullName
            if (-not $safe.StartsWith($root + '\', [StringComparison]::OrdinalIgnoreCase)) { throw 'Bytecode directory escapes the application.' }
            Get-ChildItem -LiteralPath $safe -File -Filter '*.pyc' | ForEach-Object { if (-not ($_.Attributes -band [IO.FileAttributes]::ReparsePoint)) { Remove-Item -LiteralPath $_.FullName -Force } }
            $directories[$safe]=$true
        }
    }
    foreach ($directory in @($directories.Keys | Sort-Object Length -Descending)) {
        if ((Test-Path -LiteralPath $directory -PathType Container) -and -not (Get-ChildItem -LiteralPath $directory -Force | Select-Object -First 1)) { Remove-Item -LiteralPath $directory -Force }
    }
    Write-Output "Uninstalled application. Data retained: $root"
    if (-not $Quiet) { Show-Result "卸载完成。库存、单据、备份和模型保留在：`n$root" }
} catch {
    if (-not $Quiet -and (Get-Command Show-Result -ErrorAction SilentlyContinue)) { Show-Result ("卸载未完成：" + $_.Exception.Message) $true }
    Write-Error $_.Exception.Message -ErrorAction Continue
    exit 1
}
